### ISSUE TITLE
Missing imports

### ISSUE THREAD

**Issue by joshblum** [ajslater/picopt#17]
I just ran:

```
apt-get install optipng gifsicle python-imaging
pip install picopt
```

and got this as output. Are there any extra installation steps necessary?

```
$ picopt -r *                                                           
Traceback (most recent call last):
  File "/root/Envs/bin/picopt", line 7, in <module>
    from picopt.cli import main
  File "/root/Envs/lib/python3.4/site-packages/picopt/cli.py", line 13, in <module>
    import comic
ImportError: No module named 'comic'
```

Thanks!!

**Comment by jacebrowning** [comment]
I think this package might just need a new release. `cli.py` looks different than the above stack trace.

**Comment by ajslater** [comment]
obsolete issue.
