### ISSUE TITLE
TypeError: unorderable types: NoneType() > NoneType()

### ISSUE THREAD

**Issue by msoedov** [ajslater/picopt#21]
picopt -r *.jpg
Traceback (most recent call last):
 File "/Users/msoedov/pyenvs/picopt/bin/picopt", line 11, in <module>
   sys.exit(main())
 File "/Users/msoedov/pyenvs/picopt/lib/python3.5/site-packages/picopt/cli.py", line 185, in main
   run(sys.argv)
 File "/Users/msoedov/pyenvs/picopt/lib/python3.5/site-packages/picopt/cli.py", line 180, in run
   walk.run()
 File "/Users/msoedov/pyenvs/picopt/lib/python3.5/site-packages/picopt/walk.py", line 173, in run
   record_dirs, bytes_in, bytes_out, nag_about_gifs = _walk_all_files()
 File "/Users/msoedov/pyenvs/picopt/lib/python3.5/site-packages/picopt/walk.py", line 150, in _walk_all_files
   walk_after = timestamp.get_walk_after(filename_full)
 File "/Users/msoedov/pyenvs/picopt/lib/python3.5/site-packages/picopt/timestamp.py", line 64, in get_walk_after
   optimize_after = _get_parent_timestamp(dirname, optimize_after)
 File "/Users/msoedov/pyenvs/picopt/lib/python3.5/site-packages/picopt/timestamp.py", line 45, in _get_parent_timestamp
   mtime = max(_get_timestamp(parent_pathname, False), mtime)
TypeError: unorderable types: NoneType() > NoneType()

**Comment by ajslater** [comment]
possibly fixed in 1.5.2 for python 3?
